### PR TITLE
Prioritize pip3 and pip after

### PR DESCRIPTION
**Pull request by juju4**
Required to support Ubuntu 20.04, Centos8

likely address https://github.com/neillturner/omnibus-ansible/issues/29 and https://github.com/neillturner/omnibus-ansible/issues/25

### CODE REVIEW

**Comment by juju4** [comment]
any comments/issues?
Thanks

**Comment by neillturner** [comment]
Will this break anything. comprehensive pip3 support is quite alot of work including testing.  how far does this go in implementing pip3. -)

**Comment by juju4** [comment]
I'm using it for my roles since then and no issues so far from Centos 6 to 8 and Ubuntu 16.04 to 20.04

Patch is short and just trying python3/pip3 install first, if not successful, call pip to ensure no breakage.
After, I can't say if comprehensive.

**Comment by juju4** [comment]
any issues here?
working fine on my side

**Pull request merged**
